baseurl: ""
url: "http://mediplazalosalgodones.com"

# Build settings
markdown: kramdown
encoding: utf-8

# Customs
permalink: /blog/:title/
collections:
  pages:
    output: true
    permalink: /:path/
  shop:
    output: true
    permalink: /:collection/:path/
  rest:
    output: true
    permalink: /:collection/:path/
  heal:
    output: true
    permalink: /:collection/:path/
  dine:
    output: true
    permalink: /:collection/:path/
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENSE
sass:
    sass_dir: assets/sass
    style: :compressed
    sourcemap: true
autoprefixer:
  browsers:
  - last 4 versions
gems:
  - jekyll-sitemap
  - jekyll-autoprefixer
source:      _source
destination: _build



